name = "OSRExamples"
uuid = "8df12cd0-dcc3-4a1c-8613-108dcee9c0df"
license = "MIT"
version = "0.1.0"
authors = ["Li Yifeng <mail@yifen9.li>"]

[deps]
OrcidSpringRank = "5a9d8e7c-1b2a-4c3d-9e8f-7a6b5c4d3e2f"

[sources]
OrcidSpringRank = {rev = "main", url = "https://github.com/yifen9/orcid-springrank"}
