edge: org_country
sql: |
  SELECT
    org_country_from AS src,
    org_country_to   AS dst,
    cnt_edge_weight  AS w
  FROM edge
  WHERE org_country_from IS NOT NULL
    AND org_country_to   IS NOT NULL

compute:
  alg: springrank
  Î»: 1e-8
  method: auto
  src: src
  dst: dst
  w: w
